// Code generated by protoc-gen-go.
// source: order.proto
// DO NOT EDIT!

/*
Package proto_order is a generated protocol buffer package.

It is generated from these files:
	order.proto

It has these top-level messages:
	Location
	OrderInfo
	ProcessBase
	CustomerPrice
	OrderOtherPayArgs
	OrderPayArgs
	OrderAssessArgs
	OrderCancelArgs
*/
package proto_order

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Location struct {
	// 下单坐标经度
	Lat float32 `protobuf:"fixed32,1,opt,name=lat" json:"lat,omitempty"`
	// 下单坐标纬度
	Lng float32 `protobuf:"fixed32,2,opt,name=lng" json:"lng,omitempty"`
	// 订单地址,中文名字
	OrderAddress string `protobuf:"bytes,3,opt,name=orderAddress" json:"orderAddress,omitempty"`
	// 下单区域ID，最好和APP端取的一致，可以是行政区域编码，可以是城市编码
	AreaID int32 `protobuf:"varint,4,opt,name=areaID" json:"areaID,omitempty"`
}

func (m *Location) Reset()                    { *m = Location{} }
func (m *Location) String() string            { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()               {}
func (*Location) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// OrderInfo 订单关联的物品信息(包括实际物品，故障现象, 或者里程费)
type OrderInfo struct {
	// 订单产生费用的物品ID
	GoodsID int64 `protobuf:"varint,1,opt,name=goodsID" json:"goodsID,omitempty"`
	// 物品或材料对应的故障现象ID
	ParentID int64 `protobuf:"varint,2,opt,name=parentID" json:"parentID,omitempty"`
	// 物品名称，组合名称或单个名称
	Name string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	// 物品数量
	Amount float32 `protobuf:"fixed32,4,opt,name=amount" json:"amount,omitempty"`
	// 物品单价
	Price int64 `protobuf:"varint,5,opt,name=price" json:"price,omitempty"`
	// 部件类型
	UnitType int32 `protobuf:"varint,6,opt,name=unitType" json:"unitType,omitempty"`
	// 订单信息类型 故障现象，材料，等
	InfoType int32 `protobuf:"varint,7,opt,name=infoType" json:"infoType,omitempty"`
	// 物品编码
	GoodsCode string `protobuf:"bytes,8,opt,name=goodsCode" json:"goodsCode,omitempty"`
}

func (m *OrderInfo) Reset()                    { *m = OrderInfo{} }
func (m *OrderInfo) String() string            { return proto.CompactTextString(m) }
func (*OrderInfo) ProtoMessage()               {}
func (*OrderInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// ProcessBase 订单流程基本参数
type ProcessBase struct {
	// 订单ID
	OrderID int64 `protobuf:"varint,1,opt,name=orderID" json:"orderID,omitempty"`
	// 操作订单时的坐标
	Location *Location `protobuf:"bytes,2,opt,name=location" json:"location,omitempty"`
}

func (m *ProcessBase) Reset()                    { *m = ProcessBase{} }
func (m *ProcessBase) String() string            { return proto.CompactTextString(m) }
func (*ProcessBase) ProtoMessage()               {}
func (*ProcessBase) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ProcessBase) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

// CustomerPrice 自定义设置的金额
type CustomerPrice struct {
	// 附加费
	Extra int64 `protobuf:"varint,1,opt,name=extra" json:"extra,omitempty"`
	// 辅料费
	AccessoriesFee int64 `protobuf:"varint,2,opt,name=accessoriesFee" json:"accessoriesFee,omitempty"`
}

func (m *CustomerPrice) Reset()                    { *m = CustomerPrice{} }
func (m *CustomerPrice) String() string            { return proto.CompactTextString(m) }
func (*CustomerPrice) ProtoMessage()               {}
func (*CustomerPrice) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

// OrderOtherPayArgs 订单申请代付参数
type OrderOtherPayArgs struct {
	// 订单流程基本参数 orderId, lat, lng, orderAddress
	ProcessBase *ProcessBase `protobuf:"bytes,1,opt,name=ProcessBase" json:"ProcessBase,omitempty"`
}

func (m *OrderOtherPayArgs) Reset()                    { *m = OrderOtherPayArgs{} }
func (m *OrderOtherPayArgs) String() string            { return proto.CompactTextString(m) }
func (*OrderOtherPayArgs) ProtoMessage()               {}
func (*OrderOtherPayArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *OrderOtherPayArgs) GetProcessBase() *ProcessBase {
	if m != nil {
		return m.ProcessBase
	}
	return nil
}

// OrderPayArgs 订单付款完成参数
type OrderPayArgs struct {
	// 订单流程基本参数 orderId, lat, lng, orderAddress
	ProcessBase *ProcessBase `protobuf:"bytes,1,opt,name=ProcessBase" json:"ProcessBase,omitempty"`
}

func (m *OrderPayArgs) Reset()                    { *m = OrderPayArgs{} }
func (m *OrderPayArgs) String() string            { return proto.CompactTextString(m) }
func (*OrderPayArgs) ProtoMessage()               {}
func (*OrderPayArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *OrderPayArgs) GetProcessBase() *ProcessBase {
	if m != nil {
		return m.ProcessBase
	}
	return nil
}

// OrderAssessArgs 订单评价参数
type OrderAssessArgs struct {
	// 订单流程基本参数 orderId, lat, lng, orderAddress
	ProcessBase *ProcessBase `protobuf:"bytes,1,opt,name=ProcessBase" json:"ProcessBase,omitempty"`
}

func (m *OrderAssessArgs) Reset()                    { *m = OrderAssessArgs{} }
func (m *OrderAssessArgs) String() string            { return proto.CompactTextString(m) }
func (*OrderAssessArgs) ProtoMessage()               {}
func (*OrderAssessArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *OrderAssessArgs) GetProcessBase() *ProcessBase {
	if m != nil {
		return m.ProcessBase
	}
	return nil
}

// OrderCancelArgs 订单评价参数
type OrderCancelArgs struct {
	// 订单流程基本参数 orderId, lat, lng, orderAddress
	ProcessBase *ProcessBase `protobuf:"bytes,1,opt,name=ProcessBase" json:"ProcessBase,omitempty"`
}

func (m *OrderCancelArgs) Reset()                    { *m = OrderCancelArgs{} }
func (m *OrderCancelArgs) String() string            { return proto.CompactTextString(m) }
func (*OrderCancelArgs) ProtoMessage()               {}
func (*OrderCancelArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *OrderCancelArgs) GetProcessBase() *ProcessBase {
	if m != nil {
		return m.ProcessBase
	}
	return nil
}

func init() {
	proto.RegisterType((*Location)(nil), "proto_order.Location")
	proto.RegisterType((*OrderInfo)(nil), "proto_order.OrderInfo")
	proto.RegisterType((*ProcessBase)(nil), "proto_order.ProcessBase")
	proto.RegisterType((*CustomerPrice)(nil), "proto_order.CustomerPrice")
	proto.RegisterType((*OrderOtherPayArgs)(nil), "proto_order.OrderOtherPayArgs")
	proto.RegisterType((*OrderPayArgs)(nil), "proto_order.OrderPayArgs")
	proto.RegisterType((*OrderAssessArgs)(nil), "proto_order.OrderAssessArgs")
	proto.RegisterType((*OrderCancelArgs)(nil), "proto_order.OrderCancelArgs")
}

func init() { proto.RegisterFile("order.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 384 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x51, 0x4d, 0x8f, 0xda, 0x30,
	0x10, 0x55, 0x08, 0x81, 0x30, 0xa1, 0x5f, 0x16, 0xad, 0xac, 0xaa, 0x07, 0x94, 0x43, 0xc5, 0x09,
	0xa9, 0xf4, 0xd6, 0x1b, 0x05, 0x55, 0x4a, 0x55, 0x04, 0xb2, 0x7a, 0xea, 0xa5, 0xf2, 0x26, 0x43,
	0x36, 0x2b, 0xb0, 0x23, 0xdb, 0x48, 0xcb, 0x4f, 0xdd, 0x7f, 0xb3, 0xca, 0x60, 0xbe, 0xf6, 0xba,
	0x9c, 0xe2, 0xf7, 0x66, 0xf2, 0xde, 0x9b, 0x19, 0x48, 0xb4, 0x29, 0xd0, 0x8c, 0x6b, 0xa3, 0x9d,
	0x66, 0x09, 0x7d, 0xfe, 0x13, 0x95, 0x3e, 0x40, 0xfc, 0x47, 0xe7, 0xd2, 0x55, 0x5a, 0xb1, 0xf7,
	0x10, 0x6e, 0xa4, 0xe3, 0xc1, 0x30, 0x18, 0xb5, 0x44, 0xf3, 0x24, 0x46, 0x95, 0xbc, 0xe5, 0x19,
	0x55, 0xb2, 0x14, 0xfa, 0xf4, 0xe3, 0xb4, 0x28, 0x0c, 0x5a, 0xcb, 0xc3, 0x61, 0x30, 0xea, 0x89,
	0x2b, 0x8e, 0x7d, 0x82, 0x8e, 0x34, 0x28, 0xb3, 0x39, 0x6f, 0x0f, 0x83, 0x51, 0x24, 0x3c, 0x4a,
	0x9f, 0x02, 0xe8, 0x2d, 0x9b, 0xc6, 0x4c, 0xad, 0x35, 0xe3, 0xd0, 0x2d, 0xb5, 0x2e, 0x6c, 0x36,
	0x27, 0xc7, 0x50, 0x1c, 0x21, 0xfb, 0x0c, 0x71, 0x2d, 0x0d, 0x2a, 0x97, 0xcd, 0xc9, 0x3a, 0x14,
	0x27, 0xcc, 0x18, 0xb4, 0x95, 0xdc, 0xa2, 0xf7, 0xa5, 0x37, 0xf9, 0x6d, 0xf5, 0x4e, 0x39, 0xf2,
	0x6b, 0x09, 0x8f, 0xd8, 0x00, 0xa2, 0xda, 0x54, 0x39, 0xf2, 0x88, 0x44, 0x0e, 0xa0, 0x51, 0xdf,
	0xa9, 0xca, 0xfd, 0xdd, 0xd7, 0xc8, 0x3b, 0x94, 0xef, 0x84, 0x9b, 0x5a, 0xa5, 0xd6, 0x9a, 0x6a,
	0xdd, 0x43, 0xed, 0x88, 0xd9, 0x17, 0xe8, 0x51, 0xc0, 0x99, 0x2e, 0x90, 0xc7, 0x64, 0x7f, 0x26,
	0xd2, 0x7f, 0x90, 0xac, 0x8c, 0xce, 0xd1, 0xda, 0x9f, 0xd2, 0x62, 0x33, 0x1c, 0xad, 0xe4, 0x3c,
	0x9c, 0x87, 0xec, 0x1b, 0xc4, 0x1b, 0xbf, 0x70, 0x1a, 0x2e, 0x99, 0x7c, 0x1c, 0x5f, 0x1c, 0x64,
	0x7c, 0xbc, 0x86, 0x38, 0xb5, 0xa5, 0x0b, 0x78, 0x33, 0xdb, 0x59, 0xa7, 0xb7, 0x68, 0x56, 0x34,
	0xc2, 0x00, 0x22, 0x7c, 0x74, 0x46, 0x7a, 0xed, 0x03, 0x60, 0x5f, 0xe1, 0xad, 0xcc, 0x9b, 0x04,
	0xda, 0x54, 0x68, 0x7f, 0x21, 0xfa, 0xe5, 0xbd, 0x60, 0xd3, 0x25, 0x7c, 0xa0, 0x2b, 0x2c, 0xdd,
	0x3d, 0x9a, 0x95, 0xdc, 0x4f, 0x4d, 0x69, 0xd9, 0x8f, 0xab, 0xfc, 0x24, 0x9c, 0x4c, 0xf8, 0x55,
	0xb2, 0x8b, 0xba, 0xb8, 0x6c, 0x4e, 0x7f, 0x43, 0x9f, 0x04, 0x6f, 0xa1, 0xb5, 0x80, 0x77, 0xa4,
	0x35, 0xb5, 0x16, 0xad, 0xbd, 0x99, 0xdc, 0x4c, 0xaa, 0x1c, 0x37, 0xaf, 0x95, 0xbb, 0xeb, 0x50,
	0xd7, 0xf7, 0xe7, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6e, 0xc9, 0x35, 0x7a, 0x50, 0x03, 0x00, 0x00,
}
